<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Access extends Model
{
	protected $table = 'accesses';

	public static $pages = [
		// 'export_station'           => 'Able to Export Station Log',
		'users'                    => 'Users',
		'tasks'                    => 'Tasks',
		'exports'                  => 'Export',
		'orders'                   => 'Orders',
		'orders_admin'             => 'Order Admin',
		'items'                    => 'Item List',
		'customer_service'         => 'Customer Service',
		'orders/manual'            => 'Manual Orders',
		'transfer'            		 => 'Import Orders',
		'products'                 => 'Products',
		'products_specifications'  => 'Specifications',
		'products_config'          => 'Product Config',
		'logistics'                => 'Child SKU Config',
		'stores'                   => 'Marketplace',
		'prod_report'              => 'Production Reports',
		'report'                   => 'Other Reports',
		'purchases'                => 'Purchasing',
		'inventories'              => 'Inventory',
		'inventory_admin'          => 'Inventory Admin',
		'picking'                  => 'Pick Inventory',
		'preview_batch'            => 'Create Batches',
		'batches'                  => 'View Batches',
		'graphics'                 => 'Graphics',
		'move_to_production'       => 'Move to Production',
		'reject_item'              => 'Reject Items',
		'reject_batch'             => 'Reject Entire Batch',
		'rejections'               => 'Rejects Screen',
		'backorders'               => 'Backorders',
		'summaries'                => 'Print Summaries',
		'production'               => 'Production',
		'supervisor'               => 'Supervisor',
		'move_next'                => 'Move Batches',
		'prod_config'              => 'Production Config',
		'shipping'                 => 'Shipping',
        'dhl_manifest'             => 'DHL Manifest',
        'usps/manifest'            => 'USPS Manifest',
		'wap'                      => 'WAP Screen',
		'ship_order'               => 'Shipping Admin',
	];
	
	public static $descriptions = [
		// 'export_station'           => 'Able to Export Station Log',
		'users'                    => 'manage users and permissions',
		'exports'                  => 'export orders, items',
		'orders'                   => 'view order list and details',
		'orders_admin'             => 'Delete, Change Store, quantity, description or price on orders',
		'items'                    => 'view item list',
		'customer_service'         => 'customer service screen access',
		'orders/manual'            => 'enter manual orders',
		'transfer'                 => 'import orders, export shipping notifications and invoices',
		'products'                 => 'manage products',
		'products_specifications'  => 'manage product specifications',
		'products_config'          => 'manage product categories',
		'logistics'                => 'add inventory, routes and graphic SKUs to child SKUs',
		'stores'                   => 'view and manage stores',
		'prod_report'              => 'view section report and station summary',
		'report'                   => 'profit and sales reports',
		'purchases'                => 'add and receive purchase orders, manage vendors',
		'inventories'              => 'view inventory screen',
		'inventory_admin'          => 'inventory adjustments, calculate ordering quantities, delete inventory items',
		'picking'                  => 'print inventory summary and pick inventory',
		'preview_batch'            => 'preview batch screen access',
		'batches'                  => 'batch list and details',
		'graphics'                 => 'create graphics screen access',
		'move_to_production'       => 'move printed batches to production',
		'reject_item'              => 'use reject button',
		'reject_batch'             => 'reject batch from batch screen',
		'rejections'               => 'process rejects',
		'backorders'               => 'backorder batches and mark arrived',
		'summaries'                => 'print summaries through print batch summaries screen or batch details',
		'production'               => 'scan work in a production station',
		'supervisor'               => 'move batches anywhere on route, force scan out, release batch',
		'move_next'                => 'move batches screen access',
		'prod_config'              => 'configure section, stations, routes',
		'shipping'                 => 'ship items through qc or wap',
        'dhl_manifest'             => 'DHL Manifest Discription',
        'usps/manifest'            => 'USPS Manifest',
		'wap'                      => 'WAP screen access',
		'ship_order'               => 'returned shipments, manual ship, ship from order details',
	];
}
